/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsOfSaleRouteImport } from './routes/legal.terms-of-sale'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal.mentions-legales'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as PSlugRoadmapRouteImport } from './routes/p.$slug.roadmap'
import { Route as PSlugChangelogRouteImport } from './routes/p.$slug.changelog'
import { Route as ApiPublicWidgetDotjsRouteImport } from './routes/api/public/widget[.]js'
import { Route as ApiPublicVoteRouteImport } from './routes/api/public/vote'
import { Route as ApiPublicFeedbacksRouteImport } from './routes/api/public/feedbacks'
import { Route as AuthenticatedDashboardWebhooksRouteImport } from './routes/_authenticated/dashboard.webhooks'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardReferralsRouteImport } from './routes/_authenticated/dashboard.referrals'
import { Route as AuthenticatedDashboardProjectsRouteImport } from './routes/_authenticated/dashboard.projects'
import { Route as AuthenticatedDashboardFeedbacksRouteImport } from './routes/_authenticated/dashboard.feedbacks'
import { Route as AuthenticatedDashboardFeatureRequestsRouteImport } from './routes/_authenticated/dashboard.feature-requests'
import { Route as AuthenticatedDashboardChangelogRouteImport } from './routes/_authenticated/dashboard.changelog'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfSaleRoute = LegalTermsOfSaleRouteImport.update({
  id: '/legal/terms-of-sale',
  path: '/legal/terms-of-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const PSlugRoadmapRoute = PSlugRoadmapRouteImport.update({
  id: '/p/$slug/roadmap',
  path: '/p/$slug/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugChangelogRoute = PSlugChangelogRouteImport.update({
  id: '/p/$slug/changelog',
  path: '/p/$slug/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetDotjsRoute = ApiPublicWidgetDotjsRouteImport.update({
  id: '/api/public/widget.js',
  path: '/api/public/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoteRoute = ApiPublicVoteRouteImport.update({
  id: '/api/public/vote',
  path: '/api/public/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbacksRoute = ApiPublicFeedbacksRouteImport.update({
  id: '/api/public/feedbacks',
  path: '/api/public/feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardWebhooksRoute =
  AuthenticatedDashboardWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReferralsRoute =
  AuthenticatedDashboardReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProjectsRoute =
  AuthenticatedDashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFeedbacksRoute =
  AuthenticatedDashboardFeedbacksRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFeatureRequestsRoute =
  AuthenticatedDashboardFeatureRequestsRouteImport.update({
    id: '/feature-requests',
    path: '/feature-requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChangelogRoute =
  AuthenticatedDashboardChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms-of-sale': typeof LegalTermsOfSaleRoute
  '/dashboard/changelog': typeof AuthenticatedDashboardChangelogRoute
  '/dashboard/feature-requests': typeof AuthenticatedDashboardFeatureRequestsRoute
  '/dashboard/feedbacks': typeof AuthenticatedDashboardFeedbacksRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/public/feedbacks': typeof ApiPublicFeedbacksRoute
  '/api/public/vote': typeof ApiPublicVoteRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/p/$slug/changelog': typeof PSlugChangelogRoute
  '/p/$slug/roadmap': typeof PSlugRoadmapRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms-of-sale': typeof LegalTermsOfSaleRoute
  '/dashboard/changelog': typeof AuthenticatedDashboardChangelogRoute
  '/dashboard/feature-requests': typeof AuthenticatedDashboardFeatureRequestsRoute
  '/dashboard/feedbacks': typeof AuthenticatedDashboardFeedbacksRoute
  '/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/public/feedbacks': typeof ApiPublicFeedbacksRoute
  '/api/public/vote': typeof ApiPublicVoteRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/p/$slug/changelog': typeof PSlugChangelogRoute
  '/p/$slug/roadmap': typeof PSlugRoadmapRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms-of-sale': typeof LegalTermsOfSaleRoute
  '/_authenticated/dashboard/changelog': typeof AuthenticatedDashboardChangelogRoute
  '/_authenticated/dashboard/feature-requests': typeof AuthenticatedDashboardFeatureRequestsRoute
  '/_authenticated/dashboard/feedbacks': typeof AuthenticatedDashboardFeedbacksRoute
  '/_authenticated/dashboard/projects': typeof AuthenticatedDashboardProjectsRoute
  '/_authenticated/dashboard/referrals': typeof AuthenticatedDashboardReferralsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/webhooks': typeof AuthenticatedDashboardWebhooksRoute
  '/api/public/feedbacks': typeof ApiPublicFeedbacksRoute
  '/api/public/vote': typeof ApiPublicVoteRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/p/$slug/changelog': typeof PSlugChangelogRoute
  '/p/$slug/roadmap': typeof PSlugRoadmapRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/examples'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/legal/cgu'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/legal/privacy'
    | '/legal/terms-of-sale'
    | '/dashboard/changelog'
    | '/dashboard/feature-requests'
    | '/dashboard/feedbacks'
    | '/dashboard/projects'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/webhooks'
    | '/api/public/feedbacks'
    | '/api/public/vote'
    | '/api/public/widget.js'
    | '/p/$slug/changelog'
    | '/p/$slug/roadmap'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/examples'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/legal/cgu'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/legal/privacy'
    | '/legal/terms-of-sale'
    | '/dashboard/changelog'
    | '/dashboard/feature-requests'
    | '/dashboard/feedbacks'
    | '/dashboard/projects'
    | '/dashboard/referrals'
    | '/dashboard/settings'
    | '/dashboard/webhooks'
    | '/api/public/feedbacks'
    | '/api/public/vote'
    | '/api/public/widget.js'
    | '/p/$slug/changelog'
    | '/p/$slug/roadmap'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/examples'
    | '/login'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/legal/cgu'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/legal/privacy'
    | '/legal/terms-of-sale'
    | '/_authenticated/dashboard/changelog'
    | '/_authenticated/dashboard/feature-requests'
    | '/_authenticated/dashboard/feedbacks'
    | '/_authenticated/dashboard/projects'
    | '/_authenticated/dashboard/referrals'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/webhooks'
    | '/api/public/feedbacks'
    | '/api/public/vote'
    | '/api/public/widget.js'
    | '/p/$slug/changelog'
    | '/p/$slug/roadmap'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ExamplesRoute: typeof ExamplesRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsOfSaleRoute: typeof LegalTermsOfSaleRoute
  ApiPublicFeedbacksRoute: typeof ApiPublicFeedbacksRoute
  ApiPublicVoteRoute: typeof ApiPublicVoteRoute
  ApiPublicWidgetDotjsRoute: typeof ApiPublicWidgetDotjsRoute
  PSlugChangelogRoute: typeof PSlugChangelogRoute
  PSlugRoadmapRoute: typeof PSlugRoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-sale': {
      id: '/legal/terms-of-sale'
      path: '/legal/terms-of-sale'
      fullPath: '/legal/terms-of-sale'
      preLoaderRoute: typeof LegalTermsOfSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/p/$slug/roadmap': {
      id: '/p/$slug/roadmap'
      path: '/p/$slug/roadmap'
      fullPath: '/p/$slug/roadmap'
      preLoaderRoute: typeof PSlugRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug/changelog': {
      id: '/p/$slug/changelog'
      path: '/p/$slug/changelog'
      fullPath: '/p/$slug/changelog'
      preLoaderRoute: typeof PSlugChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget.js': {
      id: '/api/public/widget.js'
      path: '/api/public/widget.js'
      fullPath: '/api/public/widget.js'
      preLoaderRoute: typeof ApiPublicWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vote': {
      id: '/api/public/vote'
      path: '/api/public/vote'
      fullPath: '/api/public/vote'
      preLoaderRoute: typeof ApiPublicVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedbacks': {
      id: '/api/public/feedbacks'
      path: '/api/public/feedbacks'
      fullPath: '/api/public/feedbacks'
      preLoaderRoute: typeof ApiPublicFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/webhooks': {
      id: '/_authenticated/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof AuthenticatedDashboardWebhooksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/referrals': {
      id: '/_authenticated/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof AuthenticatedDashboardReferralsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/projects': {
      id: '/_authenticated/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthenticatedDashboardProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/feedbacks': {
      id: '/_authenticated/dashboard/feedbacks'
      path: '/feedbacks'
      fullPath: '/dashboard/feedbacks'
      preLoaderRoute: typeof AuthenticatedDashboardFeedbacksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/feature-requests': {
      id: '/_authenticated/dashboard/feature-requests'
      path: '/feature-requests'
      fullPath: '/dashboard/feature-requests'
      preLoaderRoute: typeof AuthenticatedDashboardFeatureRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/changelog': {
      id: '/_authenticated/dashboard/changelog'
      path: '/changelog'
      fullPath: '/dashboard/changelog'
      preLoaderRoute: typeof AuthenticatedDashboardChangelogRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardChangelogRoute: typeof AuthenticatedDashboardChangelogRoute
  AuthenticatedDashboardFeatureRequestsRoute: typeof AuthenticatedDashboardFeatureRequestsRoute
  AuthenticatedDashboardFeedbacksRoute: typeof AuthenticatedDashboardFeedbacksRoute
  AuthenticatedDashboardProjectsRoute: typeof AuthenticatedDashboardProjectsRoute
  AuthenticatedDashboardReferralsRoute: typeof AuthenticatedDashboardReferralsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardWebhooksRoute: typeof AuthenticatedDashboardWebhooksRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardChangelogRoute: AuthenticatedDashboardChangelogRoute,
    AuthenticatedDashboardFeatureRequestsRoute:
      AuthenticatedDashboardFeatureRequestsRoute,
    AuthenticatedDashboardFeedbacksRoute: AuthenticatedDashboardFeedbacksRoute,
    AuthenticatedDashboardProjectsRoute: AuthenticatedDashboardProjectsRoute,
    AuthenticatedDashboardReferralsRoute: AuthenticatedDashboardReferralsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardWebhooksRoute: AuthenticatedDashboardWebhooksRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ExamplesRoute: ExamplesRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LegalCguRoute: LegalCguRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsOfSaleRoute: LegalTermsOfSaleRoute,
  ApiPublicFeedbacksRoute: ApiPublicFeedbacksRoute,
  ApiPublicVoteRoute: ApiPublicVoteRoute,
  ApiPublicWidgetDotjsRoute: ApiPublicWidgetDotjsRoute,
  PSlugChangelogRoute: PSlugChangelogRoute,
  PSlugRoadmapRoute: PSlugRoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
